from __future__ import annotations

from copy import deepcopy
from typing import Any

PERMISSIONS: list[dict[str, Any]] = [
    {
        "id": "menu-dashboard",
        "name": "工作台菜单",
        "code": "menu:dashboard",
        "type": "menu",
        "module": "dashboard",
        "description": "显示工作台菜单",
        "route": "/dashboard",
        "icon": "layout-dashboard",
        "order": 1,
    },
    {
        "id": "menu-operations",
        "name": "运营看板菜单",
        "code": "menu:operations",
        "type": "menu",
        "module": "operations",
        "description": "显示运营看板菜单",
        "route": "/operations",
        "icon": "bar-chart-3",
        "order": 2,
    },
    {
        "id": "menu-projects",
        "name": "项目中心菜单",
        "code": "menu:projects",
        "type": "menu",
        "module": "projects",
        "description": "显示项目中心菜单",
        "route": "/projects",
        "icon": "folder-kanban",
        "order": 3,
    },
    {
        "id": "menu-users",
        "name": "用户管理菜单",
        "code": "menu:users",
        "type": "menu",
        "module": "users",
        "description": "显示用户管理菜单",
        "route": "/users",
        "icon": "users",
        "order": 4,
    },
    {
        "id": "menu-roles",
        "name": "角色管理菜单",
        "code": "menu:roles",
        "type": "menu",
        "module": "roles",
        "description": "显示角色管理菜单",
        "route": "/roles",
        "icon": "shield",
        "order": 5,
    },
    {
        "id": "menu-permissions",
        "name": "权限管理菜单",
        "code": "menu:permissions",
        "type": "menu",
        "module": "permissions",
        "description": "显示权限管理菜单",
        "route": "/permissions",
        "icon": "key-round",
        "order": 6,
    },
    {
        "id": "menu-settings",
        "name": "系统配置菜单",
        "code": "menu:settings",
        "type": "menu",
        "module": "settings",
        "description": "显示系统配置菜单",
        "route": "/settings",
        "icon": "settings-2",
        "order": 7,
    },
    {
        "id": "menu-profile",
        "name": "个人中心菜单",
        "code": "menu:profile",
        "type": "menu",
        "module": "profile",
        "description": "显示个人中心菜单",
        "route": "/profile",
        "icon": "user-circle-2",
        "order": 8,
    },
    {
        "id": "page-dashboard",
        "name": "工作台页面",
        "code": "page:dashboard",
        "type": "page",
        "module": "dashboard",
        "description": "访问工作台页面",
        "route": "/dashboard",
    },
    {
        "id": "page-operations",
        "name": "运营看板页面",
        "code": "page:operations",
        "type": "page",
        "module": "operations",
        "description": "访问运营看板页面",
        "route": "/operations",
    },
    {
        "id": "page-projects",
        "name": "项目中心页面",
        "code": "page:projects",
        "type": "page",
        "module": "projects",
        "description": "访问项目中心页面",
        "route": "/projects",
    },
    {
        "id": "page-users",
        "name": "用户管理页面",
        "code": "page:users",
        "type": "page",
        "module": "users",
        "description": "访问用户管理页面",
        "route": "/users",
    },
    {
        "id": "page-roles",
        "name": "角色管理页面",
        "code": "page:roles",
        "type": "page",
        "module": "roles",
        "description": "访问角色管理页面",
        "route": "/roles",
    },
    {
        "id": "page-permissions",
        "name": "权限管理页面",
        "code": "page:permissions",
        "type": "page",
        "module": "permissions",
        "description": "访问权限管理页面",
        "route": "/permissions",
    },
    {
        "id": "page-settings",
        "name": "系统配置页面",
        "code": "page:settings",
        "type": "page",
        "module": "settings",
        "description": "访问系统配置页面",
        "route": "/settings",
    },
    {
        "id": "page-profile",
        "name": "个人中心页面",
        "code": "page:profile",
        "type": "page",
        "module": "profile",
        "description": "访问个人中心页面",
        "route": "/profile",
    },
    {
        "id": "button-user-create",
        "name": "新增用户",
        "code": "button:user:create",
        "type": "button",
        "module": "users",
        "description": "创建用户",
    },
    {
        "id": "button-user-edit",
        "name": "编辑用户",
        "code": "button:user:edit",
        "type": "button",
        "module": "users",
        "description": "编辑用户",
    },
    {
        "id": "button-user-delete",
        "name": "删除用户",
        "code": "button:user:delete",
        "type": "button",
        "module": "users",
        "description": "删除用户",
    },
    {
        "id": "button-user-assign-role",
        "name": "分配角色",
        "code": "button:user:assign-role",
        "type": "button",
        "module": "users",
        "description": "给用户分配角色",
    },
    {
        "id": "button-role-create",
        "name": "新增角色",
        "code": "button:role:create",
        "type": "button",
        "module": "roles",
        "description": "创建角色",
    },
    {
        "id": "button-role-edit",
        "name": "编辑角色",
        "code": "button:role:edit",
        "type": "button",
        "module": "roles",
        "description": "编辑角色",
    },
    {
        "id": "button-role-delete",
        "name": "删除角色",
        "code": "button:role:delete",
        "type": "button",
        "module": "roles",
        "description": "删除角色",
    },
    {
        "id": "button-role-assign-permission",
        "name": "分配权限",
        "code": "button:role:assign-permission",
        "type": "button",
        "module": "roles",
        "description": "给角色分配权限",
    },
    {
        "id": "button-permission-view",
        "name": "查看权限",
        "code": "button:permission:view",
        "type": "button",
        "module": "permissions",
        "description": "查看权限列表",
    },
    {
        "id": "button-settings-edit",
        "name": "编辑系统配置",
        "code": "button:settings:edit",
        "type": "button",
        "module": "settings",
        "description": "编辑系统配置",
    },
    {
        "id": "button-project-create",
        "name": "新建项目",
        "code": "button:project:create",
        "type": "button",
        "module": "projects",
        "description": "创建项目",
    },
    {
        "id": "button-project-edit",
        "name": "编辑项目",
        "code": "button:project:edit",
        "type": "button",
        "module": "projects",
        "description": "编辑项目",
    },
]

ROLES: list[dict[str, Any]] = [
    {
        "id": 1,
        "key": "admin",
        "name": "超级管理员",
        "description": "拥有系统全部权限",
        "permission_ids": [permission["id"] for permission in PERMISSIONS],
    },
    {
        "id": 2,
        "key": "manager",
        "name": "管理员",
        "description": "可管理业务数据，但不含删除和系统配置",
        "permission_ids": [
            "menu-dashboard",
            "menu-operations",
            "menu-projects",
            "menu-users",
            "menu-roles",
            "menu-profile",
            "page-dashboard",
            "page-operations",
            "page-projects",
            "page-users",
            "page-roles",
            "page-profile",
            "button-user-create",
            "button-user-edit",
            "button-role-create",
            "button-role-edit",
            "button-project-create",
            "button-project-edit",
        ],
    },
    {
        "id": 3,
        "key": "user",
        "name": "普通员工",
        "description": "仅能查看与自己相关的数据",
        "permission_ids": [
            "menu-dashboard",
            "menu-projects",
            "menu-profile",
            "page-dashboard",
            "page-projects",
            "page-profile",
        ],
    },
]

USERS: list[dict[str, Any]] = [
    {
        "id": 1,
        "username": "admin",
        "password": "Admin123!",
        "name": "林清远",
        "email": "admin@example.com",
        "department": "平台研发中心",
        "title": "系统负责人",
        "role_ids": [1],
        "status": "active",
        "owned_project_count": 9,
        "todo_count": 4,
        "last_login_at": "2026-06-27 09:10:00",
    },
    {
        "id": 2,
        "username": "manager",
        "password": "Manager123!",
        "name": "陈北川",
        "email": "manager@example.com",
        "department": "业务运营部",
        "title": "运营经理",
        "role_ids": [2],
        "status": "active",
        "owned_project_count": 6,
        "todo_count": 7,
        "last_login_at": "2026-06-27 08:45:00",
    },
    {
        "id": 3,
        "username": "user",
        "password": "User123!",
        "name": "周以宁",
        "email": "user@example.com",
        "department": "客户成功部",
        "title": "普通员工",
        "role_ids": [3],
        "status": "active",
        "owned_project_count": 2,
        "todo_count": 3,
        "last_login_at": "2026-06-26 18:30:00",
    },
]

PROJECTS: list[dict[str, Any]] = [
    {
        "id": 101,
        "name": "北区客户增长项目",
        "owner_user_id": 2,
        "status": "进行中",
        "progress": 68,
        "members": ["陈北川", "周以宁", "李嘉禾"],
        "visibility": "department",
    },
    {
        "id": 102,
        "name": "权限中台升级",
        "owner_user_id": 1,
        "status": "规划中",
        "progress": 32,
        "members": ["林清远", "陈北川"],
        "visibility": "company",
    },
    {
        "id": 103,
        "name": "客户分层回访专项",
        "owner_user_id": 3,
        "status": "进行中",
        "progress": 81,
        "members": ["周以宁", "王闻笙"],
        "visibility": "personal",
    },
]


def clone_users() -> list[dict[str, Any]]:
    return deepcopy(USERS)


def clone_roles() -> list[dict[str, Any]]:
    return deepcopy(ROLES)


def clone_permissions() -> list[dict[str, Any]]:
    return deepcopy(PERMISSIONS)


def clone_projects() -> list[dict[str, Any]]:
    return deepcopy(PROJECTS)
